export default function PrivacyPolicy() {
  return (
    <div className="max-w-3xl mx-auto p-4 space-y-6">
      <h1 className="text-3xl font-semibold text-center">Privacy Policy</h1>
      <p className="text-gray-600 text-sm text-center">
        Last updated: December 12, 2024
      </p>

      <p className="text-gray-700">
        This Privacy Policy describes Our policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p className="text-gray-700">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the
        <a
          href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-500 underline"
        >
          Free Privacy Policy Generator
        </a>
        .
      </p>

      <h2 className="text-2xl font-semibold text-gray-800">
        Interpretation and Definitions
      </h2>

      <h3 className="text-xl font-medium text-gray-700">Interpretation</h3>
      <p className="text-gray-700">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3 className="text-xl font-medium text-gray-700">Definitions</h3>
      <p className="text-gray-700">For the purposes of this Privacy Policy:</p>
      <ul className="list-inside list-disc space-y-2 text-gray-700">
        <li>
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is
          controlled by or is under common control with a party, where
          &quot;control&quot; means ownership of 50% or more of the shares,
          equity interest or other securities entitled to vote for election of
          directors or other managing authority.
        </li>
        <li>
          <strong>Company</strong> (referred to as either &quot;the
          Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
          this Agreement) refers to Art Film.
        </li>
        <li>
          <strong>Cookies</strong> are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </li>
        <li>
          <strong>Country</strong> refers to: Mongolia
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cellphone or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company. It refers to
          third-party companies or individuals employed by the Company to
          facilitate the Service, to provide the Service on behalf of the
          Company, to perform services related to the Service or to assist the
          Company in analyzing how the Service is used.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>Website</strong> refers to Art Film, accessible from
          <a
            href="http://artfilm.mn"
            rel="external nofollow noopener"
            target="_blank"
            className="text-blue-500 underline"
          >
            http://artfilm.mn
          </a>
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold text-gray-800">
        Collecting and Using Your Personal Data
      </h2>

      <h3 className="text-xl font-medium text-gray-700">
        Types of Data Collected
      </h3>

      <h4 className="text-lg font-semibold text-gray-700">Personal Data</h4>
      <p className="text-gray-700">
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul className="list-inside list-disc space-y-2 text-gray-700">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Usage Data</li>
      </ul>

      <h4 className="text-lg font-semibold text-gray-700">Usage Data</h4>
      <p className="text-gray-700">
        Usage Data is collected automatically when using the Service.
      </p>
      <p className="text-gray-700">
        Usage Data may include information such as Your Device's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>
      <p className="text-gray-700">
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </p>

      <h4 className="text-lg font-semibold text-gray-700">
        Tracking Technologies and Cookies
      </h4>
      <p className="text-gray-700">
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyze Our Service. The technologies We use may include:
      </p>
      <ul className="list-inside list-disc space-y-2 text-gray-700">
        <li>
          <strong>Cookies or Browser Cookies.</strong> A cookie is a small file
          placed on Your Device. You can instruct Your browser to refuse all
          Cookies or to indicate when a Cookie is being sent. However, if You do
          not accept Cookies, You may not be able to use some parts of our
          Service. Unless you have adjusted Your browser setting so that it will
          refuse Cookies, our Service may use Cookies.
        </li>
        <li>
          <strong>Web Beacons.</strong> Certain sections of our Service and our
          emails may contain small electronic files known as web beacons (also
          referred to as clear gifs, pixel tags, and single-pixel gifs) that
          permit the Company, for example, to count users who have visited those
          pages or opened an email and for other related website statistics (for
          example, recording the popularity of a certain section and verifying
          system and server integrity).
        </li>
      </ul>
      <p className="text-gray-700">
        Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies.
        Persistent Cookies remain on Your personal computer or mobile device
        when You go offline, while Session Cookies are deleted as soon as You
        close Your web browser.
      </p>

      <p className="text-gray-700">
        We use both Session and Persistent Cookies for the purposes set out
        below:
      </p>
      <ul className="list-inside list-disc space-y-2 text-gray-700">
        <li>
          <strong>Necessary / Essential Cookies</strong>
          <p>Type: Session Cookies</p>
          <p>Administered by: Us</p>
          <p>
            Purpose: These Cookies are essential to provide You with services
            available through the Website and to enable You to use some of its
            features.
          </p>
        </li>
        <li>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong>
          <p>Type: Persistent Cookies</p>
          <p>Administered by: Us</p>
          <p>
            Purpose: These Cookies identify if Users have accepted the use of
            cookies on the Website.
          </p>
        </li>
      </ul>

      <h2 className="text-2xl font-semibold text-gray-800">
        Use of Your Personal Data
      </h2>

      <p className="text-gray-700">
        The Company may use Personal Data for the following purposes:
      </p>
      <ul className="list-inside list-disc space-y-2 text-gray-700">
        <li>
          <strong>To provide and maintain Our Service</strong>, including to
          monitor the usage of Our Service.
        </li>
        <li>
          <strong>To manage Your Account</strong>: to manage Your registration
          as a user of the Service. The Personal Data You provide can give You
          access to different functionalities of the Service that are available
          to You as a registered user.
        </li>
        <li>
          <strong>To contact You</strong>: To contact You by email, phone calls,
          SMS, or other equivalent forms of electronic communication, such as a
          mobile application's push notifications regarding updates or
          informative communications related to the functionalities, products,
          or contracted services, including the security updates, when necessary
          or reasonable for their implementation.
        </li>
        <li>
          <strong>
            To provide You with news, special offers and general information
          </strong>{" "}
          about other goods, services and events which we offer that are similar
          to those that you have already purchased or inquired about unless You
          have opted not to receive such information.
        </li>
        <li>
          <strong>To manage Your requests</strong>: To attend and manage Your
          requests to Us.
        </li>
      </ul>

      <p className="text-gray-700">
        We may also process your data for other purposes, such as marketing
        activities or to comply with legal obligations. Please feel free to
        provide any additional sections you'd like to style.
      </p>
    </div>
  );
}
